name: Script Quotidien 8h

on:
  schedule:
    - cron: '*/5 * * * *' #cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execution du script
        env:
          # On lie tes Variables et Secrets aux variables d'environnement
          GH_PAT: ${{ secrets.GH_PAT }}
          MY_API_KEY: ${{ vars.MY_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          FLOOR_ID: ${{ vars.FLOOR_ID }}
          WORKSPACE_ID: ${{ vars.WORKSPACE_ID }}
        run: python auto_reservation.py
